spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 3116004646
    url: jdbc:mysql://111.230.220.64/booking?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  port: 80